{{- if not .Values.backend.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wasco-energy.backendName" . }}
  labels:
    {{- include "wasco-energy.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.secret.jwtSecret | quote }}
{{- end }}
